# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
#    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
#    -   id: check-added-large-files

#-   repo: local
#    # Ruff version is not added when using a local setup
#    hooks:
#      - id: ruff-format
#        name: Ruff Format
#        entry: ruff format .
#        language: system
#        types_or: [ python, pyi, pyproject ]
#
#      - id: ruff-lint
#        name: Ruff Lint
#        entry: ruff check .
#        language: system
#        types_or: [ python, jupyter, pyi, pyproject ]
#
#      - id: ruff-lint-fix
#        name: Ruff Lint (Autofix)
#        entry: ruff check --fix .
#        language: system
#        types: [ python, pyi, jupyter, pyproject ]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.12
    hooks:
      # Run the linter.
      - id: ruff-check
        types_or: [ python, pyi, jupyter, pyproject ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1  # use the latest stable version
    hooks:
      - id: mypy
    #args: [ --strict, --ignore-missing-imports ]
